### ISSUE TITLE
prikazati galeriju u modalu

### ISSUE THREAD

**Issue by enco164** [enco164/storyteller#1]
prikazati galeriju u modalu > izabrati/uploadovati audio > modal vraca audio > uvezati za sesiju

**Comment by milanzp** [comment]
Napravljen modal u kom se (kao privremeno resenje) iz liste biraju postojeci audio fajlovi, modal vraca audio, vezuje se...
Izgled modala (da bude "galerija") i direktan upload cekaju neke bolje dane (i Daretov uploader)
