### ISSUE TITLE
Media u bazi

### ISSUE THREAD

**Issue by enco164** [enco164/storyteller#3]
Potrebno je da se prosiri baza tako da u njoj cuvamo putanje do fajlova.
Znaci, napravi se tabela 'media' koja ima ID, filename i path. Kada se sacuva fajl u tu tabelu treba da se upise putanja do fajla.
Dalje, za svaku tabelu koja ima atribut 'path' (audioRecording, scene) treba da se izmeni i da se stavi strani kljuc ka tabeli 'media'

**Comment by milanzp** [comment]
Dok ti prodje ispit, sredicu ja to

**Comment by milanzp** [comment]
Uradjeno
